#!/usr/bin/env python3
"""Seed synthetic demo samples so a deployment is usable without private photos.

Generates deterministic, clearly-synthetic "container" images (corrugation
stripes, feature-rich speckle, lettering-like blocks — no real photographs)
plus matching engine configs into sources/ and configs/. The web tester lists
them as packaged examples automatically (configs/demo_*.json). Idempotent:
existing files are kept unless --force.

Run in the container image build (CST deployments) or manually:
    python demo_seed.py [--force]
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent
SOURCES = ROOT / "sources"
CONFIGS = ROOT / "configs"


def corrugated_panel(rng: np.random.Generator, w: int, h: int, base_bgr: tuple[int, int, int],
                     corrugation_px: int = 26, tilt: float = 0.0) -> np.ndarray:
    """One synthetic container surface: corrugation ridges + speckle + wear."""
    yy, xx = np.mgrid[0:h, 0:w]
    if tilt:
        xx = xx + tilt * (yy - h / 2)
    ridge = 0.5 + 0.5 * np.sin(2 * np.pi * xx / corrugation_px)
    plane = np.full((h, w), 0.5, np.float64)
    shade = np.clip(0.55 + 0.45 * ridge, 0, 1) * 0.75 + plane * 0.25
    img = np.empty((h, w, 3), np.float64)
    for c in range(3):
        img[..., c] = base_bgr[c] * shade
    speckle = rng.normal(0, 10, (h, w, 1))
    img = np.clip(img + speckle, 0, 255).astype(np.uint8)
    for _ in range(w * h // 900):
        x, y = int(rng.integers(2, w - 2)), int(rng.integers(2, h - 2))
        cv2.circle(img, (x, y), int(rng.integers(1, 3)),
                   (int(rng.integers(0, 255)),) * 3, -1)
    return img


def lettering(img: np.ndarray, x: int, y: int, text: str, scale: float = 1.6) -> None:
    cv2.putText(img, text, (x, y), cv2.FONT_HERSHEY_SIMPLEX, scale, (245, 245, 245),
                max(2, int(scale * 2)), cv2.LINE_AA)
    cv2.putText(img, text, (x + 2, y + 2), cv2.FONT_HERSHEY_SIMPLEX, scale, (30, 30, 30),
                max(1, int(scale)), cv2.LINE_AA)


def demo_horizontal(rng: np.random.Generator) -> tuple[Path, dict]:
    """2048x486 side view split across two camera views with a shared band."""
    w, h = 2048, 486
    surface = corrugated_panel(rng, 1500, h, (150, 120, 90), corrugation_px=30)
    lettering(surface, 380, h // 2 - 30, "DEMO 1234 5678", 1.5)
    lettering(surface, 430, h // 2 + 60, "SYNTHETIC LINE", 1.0)
    margin = np.full((h, (w - 1500) // 2, 3), 60, np.uint8)
    full = np.concatenate([margin, surface, margin], axis=1)
    src = SOURCES / "demo_horizontal.png"
    cv2.imwrite(str(src), full)
    cfg = {
        "schema_version": 2, "mode": "single", "direction": "horizontal",
        "cross_size_px": 256, "gap_px": 12, "edge_alignment": "measure",
        "sources": {"main": {"path": "../sources/demo_horizontal.png",
                             "expected_size_wh": [w, h]}},
        "containers": [{
            "key": "demo_container", "method": "edge", "same_surface_confirmed": True,
            "regions": [
                {"source": "main", "view_box": [0, 0, 1024, 486],
                 "quad": [[274, 24], [1018, 30], [1018, 458], [274, 452]]},
                {"source": "main", "view_box": [1024, 0, 2048, 486],
                 "quad": [[30, 26], [774, 22], [774, 456], [30, 460]]},
            ],
        }],
        "notes": "Synthetic demo sample generated by demo_seed.py — not a photograph.",
    }
    return src, cfg


def demo_vertical(rng: np.random.Generator) -> tuple[Path, dict]:
    """1820x2048 roof view split into stacked views."""
    w, h = 1820, 2048
    surface = corrugated_panel(rng, w, 1500, (120, 90, 140), corrugation_px=34, tilt=6.0)
    lettering(surface, 560, 1400, "DEMO ROOF", 2.0)
    top = np.full((300, w, 3), 70, np.uint8)
    bottom = np.full((h - 1800, w, 3), 70, np.uint8)
    full = np.concatenate([top, surface, bottom], axis=0)
    src = SOURCES / "demo_vertical.png"
    cv2.imwrite(str(src), full)
    cfg = {
        "schema_version": 2, "mode": "single", "direction": "vertical",
        "cross_size_px": 480, "gap_px": 12, "edge_alignment": "measure",
        "sources": {"main": {"path": "../sources/demo_vertical.png",
                             "expected_size_wh": [w, h]}},
        "containers": [{
            "key": "demo_container", "method": "edge", "same_surface_confirmed": True,
            "regions": [
                {"source": "main", "view_box": [0, 0, 1820, 1024],
                 "quad": [[40, 310], [1778, 300], [1778, 1016], [40, 1006]]},
                {"source": "main", "view_box": [0, 1024, 1820, 2048],
                 "quad": [[40, 18], [1778, 26], [1778, 740], [40, 732]]},
            ],
        }],
        "notes": "Synthetic demo sample generated by demo_seed.py — not a photograph.",
    }
    return src, cfg


def demo_rectify(rng: np.random.Generator) -> tuple[Path, dict]:
    """Single complete view — rectify only, no stitch."""
    w, h = 2048, 486
    surface = corrugated_panel(rng, 1400, h, (60, 140, 110), corrugation_px=28)
    lettering(surface, 300, h // 2, "ONE VIEW", 1.8)
    margin = np.full((h, (w - 1400) // 2, 3), 55, np.uint8)
    full = np.concatenate([margin, surface, margin], axis=1)
    src = SOURCES / "demo_rectify.png"
    cv2.imwrite(str(src), full)
    cfg = {
        "schema_version": 2, "mode": "single", "direction": "horizontal",
        "cross_size_px": 256, "gap_px": 12,
        "sources": {"main": {"path": "../sources/demo_rectify.png",
                             "expected_size_wh": [w, h]}},
        "containers": [{
            "key": "demo_container", "method": "rectify",
            "regions": [{"source": "main", "view_box": [0, 0, 2048, 486],
                         "quad": [[324, 30], [1722, 26], [1722, 460], [324, 464]]}],
        }],
        "notes": "Synthetic demo sample generated by demo_seed.py — not a photograph.",
    }
    return src, cfg


def main() -> int:
    force = "--force" in sys.argv
    SOURCES.mkdir(exist_ok=True)
    CONFIGS.mkdir(exist_ok=True)
    rng = np.random.default_rng(20260909)  # fixed seed: identical samples every build
    for name, builder in [("demo_horizontal", demo_horizontal),
                          ("demo_vertical", demo_vertical),
                          ("demo_rectify", demo_rectify)]:
        src, cfg = builder(rng)
        cfg_path = CONFIGS / f"{name}.json"
        if force or not cfg_path.is_file():
            cfg_path.write_text(__import__("json").dumps(cfg, indent=2), encoding="utf-8")
        digest = hashlib.sha256(src.read_bytes()).hexdigest()[:12]
        print(f"seeded {src.name} ({digest}) + {cfg_path.name}"
              + (" [kept existing config]" if cfg_path.is_file() and not force else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
