"""Regression, grouping, conservative overlap, CLI and rejection tests.

No test establishes automatic classification, arbitrary-camera robustness, metric
calibration or physical correctness of an edge join. Synthetic scenes and crops
provide controlled correspondence only; the three user examples use fixed corners.
"""
from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import container_stitch as cs

# The original sample photographs (sources/, examples/) are not distributed with
# this repository; tests that exercise the packaged recipes skip gracefully.
# Probe a file only the private bundle has: the seeded demo samples also live
# in sources/ during public test runs, so directory existence is not enough.
PRIVATE_BUNDLE = (ROOT / 'sources' / 'single_grey.png').is_file()


class UnifiedTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.shared = tempfile.TemporaryDirectory()
        cls.fixtures = Path(cls.shared.name)
        # Two independent textured planes with known overlap; not generated by a learned model.
        for seed in (5, 17):
            rng = np.random.default_rng(seed)
            im = rng.integers(40, 215, (220, 700, 3), dtype=np.uint8)
            im = cv2.GaussianBlur(im, (3, 3), .65)
            for i in range(50):
                x,y = int(rng.integers(10,690)),int(rng.integers(10,210))
                value = int(rng.integers(20,235))
                cv2.circle(im,(x,y),int(rng.integers(3,10)),(value,)*3,-1)
            cs.save_image(cls.fixtures / f"plane_{seed}.png", im)
            cs.save_image(cls.fixtures / f"left_{seed}.png", im[:,:450])
            cs.save_image(cls.fixtures / f"right_{seed}.png", im[:,250:])
        cs.save_image(cls.fixtures / 'blank.png', np.full((220,450,3),127,np.uint8))

    @classmethod
    def tearDownClass(cls):
        cls.shared.cleanup()

    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.base = Path(self.temp.name)
        self.counter = 0

    def tearDown(self):
        self.temp.cleanup()

    def recipe(self, name='single_grey'):
        if not PRIVATE_BUNDLE:
            raise unittest.SkipTest(
                'private sample bundle (sources/, examples/) is not part of this repository')
        config = json.loads((ROOT/'configs'/f'{name}.json').read_text())
        for source in config['sources'].values():
            source['path'] = str((ROOT/'configs'/source['path']).resolve())
        return config

    def process(self, cfg, **kwargs):
        self.counter += 1
        cpath = self.base/f'config_{self.counter}.json'
        cpath.write_text(json.dumps(cfg))
        out = self.base/f'run_{self.counter}'
        report = cs.run_job(cpath, out, **kwargs)
        return report,out

    def rejected(self, cfg, text=None, **kwargs):
        self.counter += 1
        cpath = self.base/f'config_{self.counter}.json'
        cpath.write_text(json.dumps(cfg))
        out=self.base/f'run_{self.counter}'
        with self.assertRaises(cs.ProcessingError) as ctx:
            cs.run_job(cpath,out,**kwargs)
        if text:self.assertIn(text,str(ctx.exception))
        self.assertEqual({p.name for p in out.iterdir()}
                         - {'debug_overlay.png', 'diagnostics.json', 'metrics.json', 'containers'},
                         {'report.json'})
        r=json.loads((out/'report.json').read_text())
        self.assertEqual(r['status'],'rejected')
        self.assertFalse(r['result_created'])
        self.assertFalse(r['fallback_to_edge'])
        return r

    def overlap(self, seed=5):
        q=[[0,0],[449,0],[449,219],[0,219]]
        return {'schema_version':1,'mode':'single','height':220,'gap_px':12,
                'sources':{name:{'path':str(self.fixtures/f'{name}_{seed}.png'),
                                 'expected_size_wh':[450,220]} for name in ('left','right')},
                'containers':[{'key':'box_a','container_id':'TEST-A', 'method':'overlap',
                    'same_surface_confirmed':True,
                    'matching':{'min_inliers':20,'feather_px':24},
                    'regions':[{'source':n,'quad':q} for n in ('left','right')]}]}

    def test_01_single_matches_previous_output_pixels(self):
        report,out=self.process(self.recipe())
        expected=json.loads((ROOT/'tests'/'regression_reference.json').read_text())['single_grey']
        image=cv2.imread(str(out/'result.png'),-1)
        self.assertEqual(hashlib.sha256(image.tobytes()).hexdigest(),expected['decoded_pixels_sha256'])
        self.assertEqual(report['output_size_wh'],[702,256])
        self.assertEqual(report['containers'][0]['status'],'manual_edge_join_unverified')
        self.assertFalse(report['containers'][0]['overlap_alignment_applied'])
        self.assertFalse(report['independently_verified_overlap'])

    def test_02_combo_one_matches_previous_output_pixels(self):
        report,out=self.process(self.recipe('combo_1'))
        expected=json.loads((ROOT/'tests'/'regression_reference.json').read_text())['combo_1']
        image=cv2.imread(str(out/'result.png'),-1)
        self.assertEqual(hashlib.sha256(image.tobytes()).hexdigest(),expected['decoded_pixels_sha256'])
        self.assertEqual(report['physical_container_count'],2)
        self.assertEqual(report['output_size_wh'],[1467,320])
        self.assertEqual(report['containers'][0]['container_id'],'SKLU 240755 3')
        self.assertFalse(report['cross_container_blending'])

    def test_03_combo_two_preserves_reversed_source_order(self):
        report,out=self.process(self.recipe('combo_2'))
        expected=json.loads((ROOT/'tests'/'regression_reference.json').read_text())['combo_2']
        image=cv2.imread(str(out/'result.png'),-1)
        self.assertEqual(hashlib.sha256(image.tobytes()).hexdigest(),expected['decoded_pixels_sha256'])
        self.assertEqual(report['containers'][0]['container_id'],'SKLU 055189 6')
        self.assertEqual(report['output_size_wh'],[1378,320])

    def test_04_combo_transparent_gap_no_cross_container_blend(self):
        r,out=self.process(self.recipe('combo_1'))
        im=cv2.imread(str(out/'result.png'),-1)
        sm=cv2.imread(str(out/'source_map_16bit.png'),-1)
        cm=cv2.imread(str(out/'container_map.png'),-1)
        x=r['containers'][0]['output_box_xyxy_exclusive'][2]
        self.assertTrue(np.all(im[:,x:x+12,3]==0))
        self.assertTrue(np.all(cm[:,x:x+12]==0))
        self.assertTrue(np.all(sm[:,x:x+12]==0))
        self.assertEqual(set(np.unique(sm)),{0,1,2})
        self.assertEqual(sm.dtype,np.uint16)

    def test_05_no_balance_matches_geometry_only(self):
        r,out=self.process(self.recipe(),no_balance=True)
        self.assertTrue(np.array_equal(cv2.imread(str(out/'result.png'),-1),
                                       cv2.imread(str(out/'geometry_only.png'),-1)))
        self.assertFalse(r['containers'][0]['exposure']['enabled'])

    def test_06_gray_edge_diagnostic_does_not_claim_overlap(self):
        r,out=self.process(self.recipe())
        diagnostic=r['containers'][0]['overlap_diagnostic']
        self.assertFalse(diagnostic['overlap_verified'])
        self.assertFalse(diagnostic['alignment_applied'])
        self.assertLess(diagnostic['best_mutual_unique_candidates'],4)

    def test_07_single_rejects_multiple_groups(self):
        c=self.recipe('combo_1');c['mode']='single'
        self.rejected(c,'exactly one')

    def test_08_combo_rejects_one_group(self):
        c=self.recipe();c['mode']='combo'
        self.rejected(c,'two or more')

    def test_09_no_automatic_mode(self):
        c=self.recipe();c['mode']='auto'
        self.rejected(c,'explicitly')

    def test_10_cli_mode_conflict_is_not_override(self):
        self.rejected(self.recipe(),'conflicts',mode='combo')

    def test_11_conflicting_ids_block_edge_join(self):
        c=self.recipe();g=c['containers'][0]
        g['regions'][0]['container_id']='ABCU 123456 7'
        g['regions'][1]['container_id']='XYZU 123456 7'
        self.rejected(c,'conflicting supplied IDs')

    def test_12_conflicting_ids_block_overlap(self):
        c=self.overlap();c['containers'][0]['regions'][1]['container_id']='TEST-B'
        self.rejected(c,'conflicting supplied IDs')

    def test_13_id_comparison_normalizes_spaces_and_case(self):
        c=self.recipe();g=c['containers'][0]
        g['container_id']='ABCU 123456 7'
        g['regions'][0]['container_id']='abcu1234567'
        r,_=self.process(c)
        self.assertEqual(r['physical_container_count'],1)

    def test_14_same_surface_confirmation_is_required(self):
        for method in ('edge','overlap'):
            with self.subTest(method=method):
                c=self.recipe() if method=='edge' else self.overlap()
                del c['containers'][0]['same_surface_confirmed']
                self.rejected(c,'same_surface_confirmed')

    def test_15_string_true_is_not_confirmation(self):
        c=self.recipe();c['containers'][0]['same_surface_confirmed']='true'
        self.rejected(c,'same_surface_confirmed')

    def test_16_duplicate_physical_id_groups_are_rejected(self):
        c=self.recipe('combo_1')
        c['containers'][1]['container_id']=c['containers'][0]['container_id']
        self.rejected(c,'separate physical-container groups')

    def test_17_duplicate_and_unsafe_group_keys_are_rejected(self):
        c=self.recipe('combo_1');c['containers'][1]['key']=c['containers'][0]['key']
        self.rejected(c,'keys must be unique')
        c=self.recipe();c['containers'][0]['key']='../bad'
        self.rejected(c,'safe')

    def test_18_wrong_dimensions_are_rejected(self):
        c=self.recipe();c['sources']['main']['expected_size_wh'][0]-=1
        self.rejected(c,'dimensions')

    def test_19_same_size_wrong_hash_is_rejected(self):
        c=self.recipe();c['sources']['main']['sha256']='0'*64
        self.rejected(c,'SHA-256 mismatch')

    def test_20_unknown_source_and_unknown_fields_are_rejected(self):
        c=self.recipe();c['containers'][0]['regions'][0]['source']='unknown'
        self.rejected(c,'unknown source')
        c=self.recipe();c['heigth']=256
        self.rejected(c,'Unknown job field')

    def test_21_bad_quad_shapes_and_bounds_are_rejected(self):
        for q in ([[0,0],[1,1]], [[-1,0],[20,0],[20,20],[0,20]],
                  [[0,0],[100,100],[100,0],[0,100]],
                  [[0,0],[1,0],[1,1],[0,1]]):
            with self.subTest(q=q):
                c=self.recipe();c['containers'][0]['regions'][0]['quad']=q
                self.rejected(c)

    def test_22_feature_mask_outside_surface_is_rejected(self):
        c=self.recipe();c['containers'][0]['regions'][0]['feature_quad']=[[0,0],[100,0],[100,100],[0,100]]
        self.rejected(c,'feature_quad must lie inside')

    def test_23_noninteger_view_box_is_rejected(self):
        c=self.recipe();c['containers'][0]['regions'][0]['view_box'][0]=0.5
        self.rejected(c,'integer')

    def test_24_boolean_dimensions_and_zero_combo_gap_are_rejected(self):
        c=self.recipe();c['height']=True
        self.rejected(c,'integer')
        c=self.recipe('combo_1');c['gap_px']=0
        self.rejected(c,'gap_px')

    def test_25_transparent_input_is_rejected(self):
        original=cv2.imread(str(self.fixtures/'left_5.png'))
        alpha=np.full(original.shape[:2],255,np.uint8);alpha[0,0]=0
        path=self.base/'transparent.png';cs.save_image(path,np.dstack([original,alpha]))
        c=self.overlap();c['sources']['left']['path']=str(path)
        self.rejected(c,'Transparent source')

    def test_26_sixteen_bit_input_is_rejected(self):
        path=self.base/'sixteen.png';cs.save_image(path,np.zeros((220,450),np.uint16))
        c=self.overlap();c['sources']['left']['path']=str(path)
        self.rejected(c,'8-bit')

    def test_27_existing_output_is_never_overwritten(self):
        c=self.recipe();_,out=self.process(c)
        old=(out/'report.json').read_bytes()
        with self.assertRaises(cs.ProcessingError):
            cs.run_job(ROOT/'configs'/'single_grey.json',out)
        self.assertEqual((out/'report.json').read_bytes(),old)

    def test_28_blank_overlap_rejected_without_edge_fallback(self):
        c=self.overlap()
        for info in c['sources'].values():info['path']=str(self.fixtures/'blank.png')
        report=self.rejected(c,'matches')
        self.assertEqual(report['details']['mutual_unique_candidates'],0)

    def test_29_gray_unverified_join_not_silently_upgraded(self):
        c=self.recipe();g=c['containers'][0];g['method']='overlap';g['exposure']={'enabled':False}
        self.rejected(c,'matches')

    def test_30_controlled_overlap_recovers_known_translation(self):
        r,out=self.process(self.overlap())
        m=r['containers'][0]['matching']
        H=np.asarray(m['homography_right_view_to_left_view'])
        self.assertAlmostEqual(H[0,2],250,delta=.2)
        self.assertAlmostEqual(H[1,2],0,delta=.2)
        self.assertGreater(m['inliers'],20)
        self.assertLess(m['median_reprojection_error_px'],.15)
        self.assertTrue(m['geometric_checks_passed'])
        self.assertFalse(r['independently_verified_overlap'])
        sm=cv2.imread(str(out/'source_map_16bit.png'),-1)
        self.assertTrue({1,2,3}.issubset(set(np.unique(sm))))
        im=cv2.imread(str(out/'result.png'),-1)
        self.assertTrue(np.all((sm>0)==(im[...,3]>0)))

    def test_31_real_photograph_controlled_crop_overlap(self):
        r,_=self.process(self.recipe('controlled_overlap'))
        m=r['containers'][0]['matching']
        self.assertGreaterEqual(m['inliers'],20)
        self.assertAlmostEqual(m['homography_right_view_to_left_view'][0][2],300,delta=.3)

    def test_32_reversed_overlap_order_is_rejected(self):
        c=self.overlap();c['containers'][0]['regions'].reverse()
        self.rejected(c,'extend rightward')

    def test_33_combo_independent_overlaps_never_cross_match(self):
        c=self.overlap();c['mode']='combo'
        second=self.overlap(17)
        for key,source in second['sources'].items():c['sources'][key+'_b']=source
        g=second['containers'][0];g['key']='box_b';g['container_id']='TEST-B'
        for region in g['regions']:region['source']+='_b'
        c['containers'].append(g)
        report,out=self.process(c)
        self.assertEqual(report['physical_container_count'],2)
        sm=cv2.imread(str(out/'source_map_16bit.png'),-1)
        self.assertTrue(set(np.unique(sm)).issubset({0,1,2,3,4,8,12}))
        self.assertTrue({3,12}.issubset(set(np.unique(sm))))
        for g in report['containers']:
            self.assertTrue(g['matching']['geometric_checks_passed'])

    def test_34_combo_can_mix_edge_and_overlap_per_container(self):
        c=self.overlap();c['mode']='combo'
        second=self.overlap(17)
        for k,v in second['sources'].items():c['sources'][k+'_b']=v
        g=second['containers'][0];g['key']='box_b';g['container_id']='TEST-B';g['method']='edge'
        del g['matching']
        for region in g['regions']:region['source']+='_b'
        c['containers'].append(g)
        report,_=self.process(c)
        self.assertEqual([g['method'] for g in report['containers']],['overlap','edge'])
        self.assertFalse(report['containers'][1]['overlap_alignment_applied'])

    def test_35_second_group_failure_does_not_publish_first(self):
        c=self.overlap();c['mode']='combo'
        second=copy.deepcopy(c['containers'][0]);second['key']='box_b';second['container_id']='TEST-B'
        for r in second['regions']:r['source']='blank'
        c['containers'].append(second)
        c['sources']['blank']={'path':str(self.fixtures/'blank.png'),'expected_size_wh':[450,220]}
        r=self.rejected(c,'matches')
        self.assertEqual(r['container_key'],'box_b')

    def test_36_geometry_rejects_reflection_and_projective_horizon(self):
        q=np.float32([[0,0],[100,0],[100,100],[0,100]])
        for H in [np.float64([[-1,0,100],[0,1,0],[0,0,1]]),
                  np.float64([[1,0,0],[0,1,0],[.02,0,-1]]),np.zeros((3,3))]:
            with self.assertRaises(cs.ProcessingError):cs.projected_quad(q,H)
        with self.assertRaises(cs.ProcessingError):cs.check_size(20001,100)

    def test_37_exposure_never_crosses_container_boundary(self):
        c=self.recipe('combo_1');c['containers'][0]['exposure']={'enabled':True}
        self.rejected(c,'only supported within an edge')

    def test_38_legacy_single_and_combo_configs_use_unified_runner(self):
        for name in ('single_grey','combo_1','combo_2'):
            if not PRIVATE_BUNDLE:
                self.skipTest('private sample bundle is not part of this repository')
            with self.subTest(name=name):
                cfg=ROOT/'tests'/'legacy_configs'/f'{name}.json'
                report=cs.run_job(cfg,self.base/name,input_path=ROOT/'sources'/f'{name}.png')
                image=cv2.imread(str(self.base/name/'result.png'),-1)
                expected=json.loads((ROOT/'tests'/'regression_reference.json').read_text())[name]
                self.assertEqual(hashlib.sha256(image.tobytes()).hexdigest(),expected['decoded_pixels_sha256'])
                self.assertTrue(any('Legacy config adapted' in w for w in report['warnings']))

    def test_39_repeated_job_is_deterministic_on_this_installation(self):
        _,out1=self.process(self.overlap());_,out2=self.process(self.overlap())
        self.assertEqual((out1/'result.png').read_bytes(),(out2/'result.png').read_bytes())

    def test_40_cli_success_outputs_json(self):
        if not PRIVATE_BUNDLE:
            self.skipTest('private sample bundle is not part of this repository')
        command=[sys.executable,str(ROOT/'container_stitch.py'),'--mode','combo',
                 '--config',str(ROOT/'configs'/'combo_1.json'),'--out',str(self.base/'cli')]
        run=subprocess.run(command,text=True,capture_output=True,timeout=20)
        self.assertEqual(run.returncode,0,run.stderr)
        self.assertEqual(json.loads(run.stdout)['containers'],2)

    def test_41_cli_rejection_outputs_nonzero_json_without_traceback(self):
        command=[sys.executable,str(ROOT/'container_stitch.py'),'--mode','single',
                 '--config',str(ROOT/'configs'/'combo_1.json'),'--out',str(self.base/'cli')]
        run=subprocess.run(command,text=True,capture_output=True,timeout=20)
        self.assertEqual(run.returncode,2)
        self.assertEqual(json.loads(run.stderr)['status'],'rejected')
        self.assertNotIn('Traceback',run.stderr)

    def test_42_api_returns_source_to_output_transforms(self):
        report,_=self.process(self.recipe())
        for group in report['containers']:
            for region in group['regions']:
                H=np.asarray(region['input_to_final_homography'])
                self.assertEqual(H.shape,(3,3));self.assertTrue(np.isfinite(H).all())
                x0,y0,_,_=region['view_box_xyxy_exclusive']
                q=np.asarray(region['quad_tl_tr_br_bl_in_view'])+np.array([x0,y0])
                out=cv2.perspectiveTransform(q[None].astype(np.float64),H)[0]
                self.assertGreaterEqual(float(out.min()),-1e-4)
                self.assertLessEqual(float(out[:,0].max()),report['output_size_wh'][0])

    def test_43_multi_source_input_override_requires_names(self):
        self.rejected(self.overlap(),'one-source job',input_path=self.fixtures/'left_5.png')

    def test_44_masked_warp_does_not_sample_unselected_colors(self):
        image=np.zeros((50,100,3),np.uint8);image[:]=(0,0,255);image[10:41,20:81]=(100,100,100)
        q=np.float32([[20,10],[80,10],[80,40],[20,40]])
        H,size=cs.rectification(q,60)
        p,v=cs.warp(image,cs.mask_for(image.shape[:2],q),H,size)
        self.assertTrue(np.allclose(p[v],100,atol=.01))

    def test_45_unknown_named_source_override_is_rejected(self):
        self.rejected(self.recipe(),'unknown source',source_overrides={'unknown':self.fixtures/'left_5.png'})

    def test_46_invalid_balance_parameters_do_not_leave_partial_results(self):
        c=self.recipe();c['containers'][0]['exposure']['max_gain']=float('nan')
        self.rejected(c,'finite')

    def test_47_cli_bad_source_syntax_is_rejected(self):
        args=[sys.executable,str(ROOT/'container_stitch.py'),'--config',str(ROOT/'configs'/'single_grey.json'),
              '--out',str(self.base/'cli'),'--source','bad']
        run=subprocess.run(args,text=True,capture_output=True,timeout=20)
        self.assertEqual(run.returncode,2)
        self.assertEqual(json.loads(run.stderr)['status'],'rejected')

    def test_48_supported_methods_have_exact_region_cardinality(self):
        c=self.recipe('combo_1');c['containers'][0]['regions']*=2
        self.rejected(c,'exactly 1')
        c=self.recipe();c['containers'][0]['regions']=c['containers'][0]['regions'][:1]
        self.rejected(c,'exactly 2')


if __name__=='__main__':unittest.main(verbosity=2)
